<?php
//
// SourceForge: Breaking Down the Barriers to Open Source Development
// Copyright 1999-2000 (c) The SourceForge Crew
// http://sourceforge.net
//
// $Id: index.php,v 1.7 2000/05/17 21:51:55 tperdue Exp $

require "pre.php";    
site_header(array(title=>"Exports Available"));
?>
<P>SourceForge data is exported in a variety of standard formats. Many of
the export URLs can also accept form/get data to customize the output. All
data generated by these pages is realtime.
<P><B>News Data</B>
<UL>
<LI><A href="rss_sfnews.php">SourceForge Front Page/Project News</A>
(<A href="http://my.netscape.com/publish/formats/rss-spec-0.91.html">RSS 0.91</A>,
<A href="http://my.netscape.com/publish/formats/rss-0.91.dtd">&lt;rss-0.91.dtd&gt;</A>)
<LI><A href="rss_sfnewreleases.php">SourceForge New Releases</A>
(<A href="http://my.netscape.com/publish/formats/rss-spec-0.91.html">RSS 0.91</A>,
<A href="http://my.netscape.com/publish/formats/rss-0.91.dtd">&lt;rss-0.91.dtd&gt;</A>)
</UL>
<P><B>Listings</B>
<UL>
<LI><A href="rss_sfprojects.php">SourceForge Full Project Listing</A>
(<A href="http://my.netscape.com/publish/formats/rss-spec-0.91.html">RSS 0.91</A>,
<A href="http://my.netscape.com/publish/formats/rss-0.91.dtd">&lt;rss-0.91.dtd&gt;</A>)
</UL>
<P><B>Project Information</B>
<UL>
<LI><A href="nitf_sfforums.php">Project Forums</A>, ?group_id required
(<A href="sf_forum_0.1.dtd.txt">&lt;sf_forum_0.1.dtd&gt;</A>)
</UL>
<?php
site_footer(array());

?>
